## Code to generate Figure 4 of the paper using the optimal parameters obtained from the ML for both the full model
## and the model that does not contain a term for the correlation between the linear terms. 
## Note that since the confidence intervals are obtained by bootstrapping, the figure generated by this script
## might differ slightly from the figure in the paper.

## 2018 05 14
## Anders Ledberg: anders.ledberg@gmail.com 


## this script depends on that loadInsarkData.R has been run

library(data.table)
library(ggplot2)
library(grid)
library(gridExtra)
library(boot)


data<-data.table(data)

## generate the conditional data
datcond<-data[,list("mk"=mean(knst),"vk"=var(knst),"mh"=mean(hgrp),"vh"=var(hgrp),"cov"=cov(hgrp,knst),"N"=.N),by=weight]



###################################################################################
## load the optimimal parameters for the 12 parameter fit
xinit=read.table("optimal_params12.txt")
xinit<-xinit[,1]

## generate the predicted responses
pred<-as.data.frame(datcond[,weight])
names(pred)<-"weight"
pred$N<-datcond$N

## predicted means
pred$mk<-pred$weight*xinit[3]+xinit[1]
pred$mh<-pred$weight*xinit[4]+xinit[2]
## approximate 95% confidence intervals
pred$mkUpper<-datcond$mk+2*sqrt(xinit[5]+xinit[8]*datcond$weight*datcond$weight + 2*xinit[11]*datcond$weight)/sqrt(pred$N)
pred$mkLower<-datcond$mk-2*sqrt(xinit[5]+xinit[8]*datcond$weight*datcond$weight+2*xinit[11]*datcond$weight)/sqrt(pred$N)
pred$mhUpper<-datcond$mh+2*sqrt(xinit[7]+xinit[10]*datcond$weight*datcond$weight+2*xinit[12]*datcond$weight)/sqrt(pred$N)
pred$mhLower<-datcond$mh-2*sqrt(xinit[7]+xinit[10]*datcond$weight*datcond$weight+2*xinit[12]*datcond$weight)/sqrt(pred$N)

## predicted variances
pred$vk<-pred$weight*pred$weight*xinit[8]+xinit[5]+2*xinit[11]*pred$weight
pred$vh<-pred$weight*pred$weight*xinit[10]+xinit[7]+2*xinit[12]*pred$weight
## even more approximated CIs, based on the Chi^2 distribution
pred$vkUpper<-(datcond$vk)*(pred$N-1)/qchisq(1-0.975,df=pred$N-1)
pred$vkLower<-(datcond$vk)*(pred$N-1)/qchisq(0.975,df=pred$N-1)
pred$vhUpper<-(datcond$vh)*(pred$N-1)/qchisq(1-0.975,df=pred$N-1)
pred$vhLower<-(datcond$vh)*(pred$N-1)/qchisq(0.975,df=pred$N-1)

## estimate confidence intervals with bootstrapping 
zlevels=pred$weight
nboot=1000

condvar<-function(data,indx){
    vh=var(data$hgrp[indx])
    vk=var(data$knst[indx])
    return(c(vh,vk))
}

pred$vkUpperBoot=0
pred$vkLowerBoot=0
pred$vhUpperBoot=0
pred$vhLowerBoot=0

for (i in 1:length(zlevels)){
    tmpd<-data[data$weight==zlevels[i],]
    bres<-boot(data=tmpd,statistic=condvar,R=nboot)
    cis=boot.ci(bres,type="basic")
    pred$vhUpperBoot[i]=cis$basic[5]
    pred$vhLowerBoot[i]=cis$basic[4]
    cis=boot.ci(bres,type="basic",index=2)
    pred$vkUpperBoot[i]=cis$basic[5]
    pred$vkLowerBoot[i]=cis$basic[4]
}



## predicted covariances
pred$cov<-xinit[6]+2*pred$weight*xinit[9]

## and bootstrap to get CI-s for covariance
condcov<-function(data,indx){
    return(cov(data$hgrp[indx],data$knst[indx]))
}

pred$covUpper=0
pred$covLower=0
for (i in 1:length(zlevels)){
    tmpd<-data[data$weight==zlevels[i],]
    bres<-boot(data=tmpd,statistic=condcov,R=nboot)
    cis=boot.ci(bres,type="basic",index=1)
    pred$covUpper[i]=cis$basic[5]
    pred$covLower[i]=cis$basic[4]
}



#######################################################################################
## now do the predictions for the 13 parameter case



## load the optimimal parameters
xinit=read.table("optimal_params13.txt")
xinit<-xinit[,1]

## generate the predicted responses
pred13<-as.data.frame(datcond[,weight])
names(pred13)<-"weight"
pred13$N<-datcond$N

## predicted means
pred13$mk<-pred13$weight*xinit[3]+xinit[1]
pred13$mh<-pred13$weight*xinit[4]+xinit[2]
## approximate 95% confidence intervals
pred13$mkUpper<-datcond$mk+2*sqrt(xinit[5]+xinit[8]*datcond$weight*datcond$weight + 2*xinit[11]*datcond$weight)/sqrt(pred13$N)
pred13$mkLower<-datcond$mk-2*sqrt(xinit[5]+xinit[8]*datcond$weight*datcond$weight+2*xinit[11]*datcond$weight)/sqrt(pred13$N)
pred13$mhUpper<-datcond$mh+2*sqrt(xinit[7]+xinit[10]*datcond$weight*datcond$weight+2*xinit[12]*datcond$weight)/sqrt(pred13$N)
pred13$mhLower<-datcond$mh-2*sqrt(xinit[7]+xinit[10]*datcond$weight*datcond$weight+2*xinit[12]*datcond$weight)/sqrt(pred13$N)

## predicted variances
pred13$vk<-pred13$weight*pred13$weight*xinit[8]+xinit[5]+2*xinit[11]*pred13$weight
pred13$vh<-pred13$weight*pred13$weight*xinit[10]+xinit[7]+2*xinit[12]*pred13$weight
## even more approximated CIs, based on the Chi^2 distribution
pred13$vkUpper<-(datcond$vk)*(pred13$N-1)/qchisq(1-0.975,df=pred13$N-1)
pred13$vkLower<-(datcond$vk)*(pred13$N-1)/qchisq(0.975,df=pred13$N-1)
pred13$vhUpper<-(datcond$vh)*(pred13$N-1)/qchisq(1-0.975,df=pred13$N-1)
pred13$vhLower<-(datcond$vh)*(pred13$N-1)/qchisq(0.975,df=pred13$N-1)

## estimate confidence intervals with bootstrapping 

zlevels=pred13$weight
nboot=1000

condvar<-function(data,indx){
    vh=var(data$hgrp[indx])
    vk=var(data$knst[indx])
    return(c(vh,vk))
}

pred13$vkUpperBoot=0
pred13$vkLowerBoot=0
pred13$vhUpperBoot=0
pred13$vhLowerBoot=0

for (i in 1:length(zlevels)){
    tmpd<-data[data$weight==zlevels[i],]
    bres<-boot(data=tmpd,statistic=condvar,R=nboot)
    cis=boot.ci(bres,type="basic")
    pred13$vhUpperBoot[i]=cis$basic[5]
    pred13$vhLowerBoot[i]=cis$basic[4]
    cis=boot.ci(bres,type="basic",index=2)
    pred13$vkUpperBoot[i]=cis$basic[5]
    pred13$vkLowerBoot[i]=cis$basic[4]
}



## predicted covariances
pred13$cov<-pred13$weight*pred13$weight*xinit[9]+xinit[6]+2*pred13$weight*xinit[13]

## and bootstrap to get CI-s for covariance
condcov<-function(data,indx){
    return(cov(data$hgrp[indx],data$knst[indx]))
}

pred13$covUpper=0
pred13$covLower=0
for (i in 1:length(zlevels)){
    tmpd<-data[data$weight==zlevels[i],]
    bres<-boot(data=tmpd,statistic=condcov,R=nboot)
    cis=boot.ci(bres,type="basic",index=1)
    pred13$covUpper[i]=cis$basic[5]
    pred13$covLower[i]=cis$basic[4]
}


##################################################################################3
##################################################################################3
## plot the conditional means

msize=0.4
tsize=4.5
titsize=20
fface="bold"
tface="plain"
xpos=66
hjust=-0.2
textsize=18
atextsize=14
## size of dashes
dsize=0.4
## size of dots
dotsize=0.4


pl1<-ggplot(datcond,aes(x=weight,y=mh))+geom_point(size=2)+ylab("Mean (N)")+xlab("Weight (kg)")+geom_line(data=pred,size=dotsize,aes(y=mh,x=weight),linetype="dotted")+geom_errorbar(data=pred,aes(ymin=mhLower,ymax=mhUpper),width=0.3)+theme(axis.text=element_text(size=atextsize),axis.title=element_text(size=textsize),strip.text.x=element_text(size=textsize),legend.text=element_text(size=textsize),legend.key.size=unit(16, "points"),legend.title=element_text(size=textsize),plot.margin = unit(c(msize,msize,msize,msize), "cm"),plot.title = element_text(hjust=hjust,size=titsize,face=fface))+ggtitle("A")+geom_text(x=xpos,y=645,label="grip strength",check_overlap=FALSE,fontface=tface,size=tsize)+geom_line(data=pred13,size=dsize,aes(y=mh,x=weight),linetype="longdash")


pl2<-ggplot(datcond,aes(x=weight,y=mk))+geom_point(size=2)+ylab("Mean (N)")+xlab("Weight (kg)")+geom_line(data=pred,size=dotsize,aes(y=mk,x=weight),linetype="dotted")+geom_errorbar(data=pred,aes(ymin=mkLower,ymax=mkUpper),width=0.3)+theme(axis.text=element_text(size=atextsize),axis.title=element_text(size=textsize),strip.text.x=element_text(size=textsize),legend.text=element_text(size=textsize),legend.key.size=unit(16, "points"),legend.title=element_text(size=textsize),plot.margin = unit(c(msize,msize,msize,msize), "cm"))+theme(plot.margin = unit(c(msize,msize,msize,msize), "cm"),plot.title = element_text(hjust=hjust,size=titsize,face=fface))+ggtitle("B")+geom_text(x=xpos,y=614,label="knee strength",check_overlap=FALSE,fontface=tface,size=tsize)+geom_line(data=pred13,size=dsize,aes(y=mk,x=weight),linetype="longdash")


##################################################################################
## plot the conditional variances

pl3<-ggplot(datcond,aes(x=weight,y=vh))+geom_point(size=2)+ylab("Variance (N^2)")+xlab("Weight (kg)")+geom_line(data=pred,size=dotsize,aes(y=vh,x=weight),linetype="dotted")+geom_errorbar(data=pred,aes(ymin=vhLowerBoot,ymax=vhUpperBoot),width=0.3)+theme(axis.text=element_text(size=atextsize),axis.title=element_text(size=textsize),strip.text.x=element_text(size=textsize),legend.text=element_text(size=textsize),legend.key.size=unit(16, "points"),legend.title=element_text(size=textsize),plot.margin = unit(c(msize,msize,msize,msize), "cm"),plot.title = element_text(hjust=hjust+hjust/6,size=titsize,face=fface))+ggtitle("C")+geom_text(x=xpos,y=8250,label="grip strength",check_overlap=FALSE,fontface=tface,size=tsize)+geom_line(data=pred13,size=dsize,aes(y=vh,x=weight),linetype="longdash")

pl4<-ggplot(datcond,aes(x=weight,y=vk))+geom_point(size=2)+ylab("Variance (N^2)")+xlab("Weight (kg)")+geom_line(data=pred,size=dotsize,aes(y=vk,x=weight),linetype="dotted")+geom_errorbar(data=pred,aes(ymin=vkLowerBoot,ymax=vkUpperBoot),width=0.3)+theme(axis.text=element_text(size=atextsize),axis.title=element_text(size=textsize),strip.text.x=element_text(size=textsize),legend.text=element_text(size=textsize),legend.key.size=unit(16, "points"),legend.title=element_text(size=textsize),plot.margin = unit(c(msize,msize,msize,msize), "cm"),plot.title = element_text(hjust=hjust+hjust/5,size=titsize,face=fface))+ggtitle("D")+geom_text(x=xpos,y=13030,label="knee strength",check_overlap=FALSE,fontface=tface,size=tsize)+geom_line(data=pred13,size=dsize,aes(y=vk,x=weight),linetype="longdash")


##################################################################################
## plot the conditional co-variances

pl5<-ggplot(datcond,aes(x=weight,y=cov))+geom_point(size=2)+ylab("Covariance (N^2)")+xlab("Weight (kg)")+geom_line(data=pred,size=dotsize,aes(y=cov,x=weight),linetype="dotted")+geom_errorbar(data=pred,aes(ymin=covLower,ymax=covUpper),width=0.3)+theme(axis.text=element_text(size=atextsize),axis.title=element_text(size=textsize),strip.text.x=element_text(size=textsize),legend.text=element_text(size=textsize),legend.key.size=unit(16, "points"),legend.title=element_text(size=textsize),plot.margin = unit(c(msize,msize,msize,msize), "cm"),plot.title = element_text(hjust=hjust/2,size=titsize,face=fface))+ggtitle("E")+geom_line(data=pred13,size=dsize,aes(y=cov,x=weight),linetype="longdash")


lay=rbind(c(1,2),c(3,4),c(5,5))
grid.arrange(pl1,pl2,pl3,pl4,pl5,layout_matrix=lay)


fn="figure1_12and13par.pdf"
dev.copy2pdf(file=fn,out.type="cairo", width=10, height=12)
